[package]
name = "dotenv"
version = "0.0.1"
entrypoint = "lib.typ"
authors = ["chillcicada"]
license = "MIT"
description = "Load environment variables from a .env file."
homepage = "https://github.com/chillcicada/typst-dotenv#readme"
repository = "https://github.com/chillcicada/typst-dotenv"
keywords = ["dotenv", "environment"]
exclude = ["example"]
